# Generated by Django 4.2.6 on 2023-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Computadoras de mesa', 'Computadoras de mesa'), ('Perifericos', 'Perifericos')], max_length=30),
        ),
    ]
