# Generated by Django 4.2.6 on 2023-11-03 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesent', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=120)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMISOR', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
