# Generated by Django 4.2.6 on 2023-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='dni',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
